BEGIN {
S["am__EXEEXT_FALSE"]=""
S["am__EXEEXT_TRUE"]="#"
S["LTLIBOBJS"]=""
S["LIBOBJS"]=""
S["HAVE_LONG_DOUBLE_FALSE"]="#"
S["HAVE_LONG_DOUBLE_TRUE"]=""
S["libc_cv_cc_loop_to_function"]="yes"
S["libc_cv_initfinit_array"]="yes"
S["CC_FOR_BUILD"]="gcc"
S["STDIO64_OBJECTLIST"]=""
S["UNIX_OBJECTLIST"]=""
S["SYSCALL_OBJECTLIST"]="libc/syscalls/objectlist.awk.in"
S["SIGNAL_OBJECTLIST"]="libc/signal/objectlist.awk.in"
S["POSIX_OBJECTLIST"]=""
S["SYS_MACH_OBJECTLIST"]=""
S["SYS_OBJECTLIST"]="libc/sys/arm/objectlist.awk.in"
S["MACHINE_OBJECTLIST"]="libc/machine/arm/objectlist.awk.in"
S["LIBM_MACHINE_OBJECTLIST"]="libm/machine/arm/objectlist.awk.in"
S["CRT1_DIR"]=""
S["CRT1"]=""
S["CRT0_DIR"]="libc/"
S["CRT0"]="crt0.o"
S["HAVE_CRT0_FALSE"]="#"
S["HAVE_CRT0_TRUE"]=""
S["EXTRA_DIRS"]=""
S["HAVE_MULTISUBDIR_FALSE"]=""
S["HAVE_MULTISUBDIR_TRUE"]="#"
S["HAVE_DOC_FALSE"]="#"
S["HAVE_DOC_TRUE"]=""
S["subdirs"]=" libc libm doc"
S["CC_FOR_NEWLIB"]="arm-none-eabi-gcc -B/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/newlib/ -isystem /home/grumic/MUTTERS-Bootload"\
"er/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/newlib/targ-include -isystem /home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0."\
"0/newlib/libc/include -B/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/libgloss/arm -L/home/grumic/MUTTERS-Bootlo"\
"ader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/libgloss/libnosys -L/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/libgl"\
"oss/arm   "
S["NEWLIB_HW_FP_FALSE"]=""
S["NEWLIB_HW_FP_TRUE"]="#"
S["CPP"]=""
S["OTOOL64"]=""
S["OTOOL"]=""
S["LIPO"]="arm-none-eabi-lipo"
S["NMEDIT"]=""
S["DSYMUTIL"]=""
S["LN_S"]=""
S["NM"]="arm-none-eabi-nm"
S["ac_ct_DUMPBIN"]=""
S["DUMPBIN"]=""
S["LD"]="arm-none-eabi-ld"
S["FGREP"]=""
S["EGREP"]=""
S["GREP"]=""
S["EXEEXT"]=""
S["ac_ct_CC"]=""
S["CPPFLAGS"]=""
S["CFLAGS"]="-g -O2"
S["LIBTOOL"]=""
S["OBJDUMP"]="arm-none-eabi-objdump"
S["DLLTOOL"]="arm-none-eabi-dlltool"
S["SED"]="/bin/sed"
S["sys_dir"]="arm"
S["machine_dir"]="arm"
S["libm_machine_dir"]="arm"
S["lpfx"]="lib_a-"
S["aext"]="a"
S["oext"]="o"
S["OBJEXT"]="o"
S["USE_LIBTOOL_FALSE"]=""
S["USE_LIBTOOL_TRUE"]="#"
S["ELIX_LEVEL_4_FALSE"]=""
S["ELIX_LEVEL_4_TRUE"]="#"
S["ELIX_LEVEL_3_FALSE"]=""
S["ELIX_LEVEL_3_TRUE"]="#"
S["ELIX_LEVEL_2_FALSE"]=""
S["ELIX_LEVEL_2_TRUE"]="#"
S["ELIX_LEVEL_1_FALSE"]=""
S["ELIX_LEVEL_1_TRUE"]="#"
S["ELIX_LEVEL_0_FALSE"]="#"
S["ELIX_LEVEL_0_TRUE"]=""
S["LDFLAGS"]=""
S["NO_INCLUDE_LIST"]=" rpc/types.h rpc/xdr.h"
S["NEWLIB_CFLAGS"]=" -DARM_RDI_MONITOR -fno-builtin"
S["CCASFLAGS"]="-g -O2"
S["CCAS"]="arm-none-eabi-gcc -B/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/newlib/ -isystem /home/grumic/MUTTERS-Bootload"\
"er/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/newlib/targ-include -isystem /home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0."\
"0/newlib/libc/include -B/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/libgloss/arm -L/home/grumic/MUTTERS-Bootlo"\
"ader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/libgloss/libnosys -L/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/libgl"\
"oss/arm   "
S["MAINT"]="#"
S["MAINTAINER_MODE_FALSE"]=""
S["MAINTAINER_MODE_TRUE"]="#"
S["READELF"]="arm-none-eabi-readelf"
S["RANLIB"]="arm-none-eabi-ranlib"
S["AR"]="arm-none-eabi-ar"
S["AS"]="arm-none-eabi-as"
S["am__fastdepCC_FALSE"]="#"
S["am__fastdepCC_TRUE"]=""
S["CCDEPMODE"]="depmode=gcc3"
S["am__nodep"]="_no"
S["AMDEPBACKSLASH"]="\\"
S["AMDEP_FALSE"]="#"
S["AMDEP_TRUE"]=""
S["am__quote"]=""
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["CC"]="arm-none-eabi-gcc -B/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/newlib/ -isystem /home/grumic/MUTTERS-Bootload"\
"er/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/newlib/targ-include -isystem /home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0."\
"0/newlib/libc/include -B/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/libgloss/arm -L/home/grumic/MUTTERS-Bootlo"\
"ader/tms570LC4357ZWT/newlib/newlib-3.0.0/arm-none-eabi/libgloss/libnosys -L/home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/libgl"\
"oss/arm   "
S["am__untar"]="$${TAR-tar} xf -"
S["am__tar"]="$${TAR-tar} chof - \"$$tardir\""
S["AMTAR"]="$${TAR-tar}"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="gawk"
S["mkdir_p"]="/bin/mkdir -p"
S["MKDIR_P"]="/bin/mkdir -p"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["STRIP"]="arm-none-eabi-strip"
S["install_sh"]="${SHELL} /home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/install-sh"
S["MAKEINFO"]="makeinfo --split-size=5000000"
S["AUTOHEADER"]="${SHELL} /home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/missing --run autoheader"
S["AUTOMAKE"]="${SHELL} /home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/missing --run automake-1.11"
S["AUTOCONF"]="${SHELL} /home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/missing --run autoconf"
S["ACLOCAL"]="${SHELL} /home/grumic/MUTTERS-Bootloader/tms570LC4357ZWT/newlib/newlib-3.0.0/missing --run aclocal-1.11"
S["VERSION"]="3.0.0"
S["PACKAGE"]="newlib"
S["CYGPATH_W"]="echo"
S["am__isrc"]=" -I$(srcdir)"
S["INSTALL_DATA"]="/usr/bin/install -c -m 644"
S["INSTALL_SCRIPT"]="/usr/bin/install -c"
S["INSTALL_PROGRAM"]="/usr/bin/install -c"
S["host_os"]="eabi"
S["host_vendor"]="none"
S["host_cpu"]="arm"
S["host"]="arm-none-eabi"
S["build_os"]="linux-gnu"
S["build_vendor"]="pc"
S["build_cpu"]="x86_64"
S["build"]="x86_64-pc-linux-gnu"
S["newlib_basedir"]="../.././newlib/."
S["MAY_SUPPLY_SYSCALLS_FALSE"]="#"
S["MAY_SUPPLY_SYSCALLS_TRUE"]=""
S["target_alias"]="arm-none-eabi"
S["host_alias"]="arm-none-eabi"
S["build_alias"]="x86_64-pc-linux-gnu"
S["LIBS"]=""
S["ECHO_T"]=""
S["ECHO_N"]="-n"
S["ECHO_C"]=""
S["DEFS"]="-DHAVE_CONFIG_H"
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE_TARNAME}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s&^&arm-none-eabi-&"
S["prefix"]="/usr/local"
S["exec_prefix"]="${prefix}"
S["PACKAGE_URL"]=""
S["PACKAGE_BUGREPORT"]=""
S["PACKAGE_STRING"]="newlib 3.0.0"
S["PACKAGE_VERSION"]="3.0.0"
S["PACKAGE_TARNAME"]="newlib"
S["PACKAGE_NAME"]="newlib"
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/bash"
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

